# Generated by Django 6.0.3 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_renter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
