# Generated by Django 6.0.3 on 2026-03-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_equipment_current_renter_equipment_is_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='owner_phone',
            field=models.CharField(default='254700000000', max_length=15),
        ),
    ]
