# Generated by Django 6.0.3 on 2026-03-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_equipment_owner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
