# Generated by Django 6.0.3 on 2026-03-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_equipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='Idle', max_length=20),
        ),
    ]
