# Generated by Django 6.0.3 on 2026-03-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='owner_phone',
        ),
    ]
